PYTHON = sage --python

doc-html:
	make -C doc html

doc-latexpdf:
	make -C doc latex

example-QFT:
	cd examples; $(PYTHON) QFT-4-1-1.py

example-graphstates:
	cd examples; $(PYTHON) hypergraphstate-3-3.py